name: mpabot_so_parser

services:
  so-parser-web:
    container_name: so-parser-web
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=so-parser-backend:9091
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
    depends_on:
      - so-parser-backend
    networks:
      - subnet

  so-parser-backend:
    container_name: so-parser-backend
    image: stackoverflow_parsing_service_backend
    build:
      context: app
      target: builder
    # app requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
      - MONGO_URI=mongodb://so-parser-mongo:27017/so-parser_db
    volumes:
      - ./app:/src
    depends_on:
      -  so-parser-mongo
    networks:
      - subnet
      - data-net

  so-parser-mongo:
    container_name: so-parser-mongo
    image: mongo
    ports:
      - 50002:27017
    volumes:
      - so-parser-data:/data/db
    networks:
      - subnet

networks:
  subnet:
    driver: bridge
  data-net:
    external:
      name: mpabot_data_controller_data-net

volumes:
  so-parser-data: